version: '3.9'
services:
  postgres:
    image: postgres:12.2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "65432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  cuenta-clientes:
    build: .
    restart: always
    ports:
      - "1203:1203"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:65432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      
  cuenta-transacciones:
    build: .
    restart: always
    ports:
      - "1204:1204"
    depends_on:
      - postgres
      - cuenta-clientes
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:65432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres