version: '3.9'
services:
  postgres:
    image: postgres:12.2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "65432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./BD_SCRIPTS:/docker-entrypoint-initdb.d


  cliente-persona:
    build:
      context: ./cliente-persona
      dockerfile: Dockerfile
    restart: always
    ports:
      - "1203:1203"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      
  cuenta-movimiento:
    build:
      context: ./cuenta-movimiento
      dockerfile: Dockerfile
    restart: always
    ports:
      - "1204:1204"
    depends_on:
      - postgres
      - cliente-persona
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres